# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class PlayerdatascraperItem(scrapy.Item):
    # define the fields for your item here like:
    name = scrapy.Field()
    id = scrapy.Field()
    start_year = scrapy.Field()
    end_year = scrapy.Field()
    birth_date = scrapy.Field()
    birth_month = scrapy.Field()
    birth_year = scrapy.Field()
    age = scrapy.Field()
    curr_age = scrapy.Field()
    team = scrapy.Field()
    league = scrapy.Field()
    position = scrapy.Field()
    games_played = scrapy.Field()
    games_started = scrapy.Field()
    FG_percent = scrapy.Field()
    three_P_percent = scrapy.Field()
    two_P_percent = scrapy.Field()
    eFG_percent = scrapy.Field()
    FT_percent = scrapy.Field()

    total_MP = scrapy.Field()
    total_FGM = scrapy.Field()
    total_FGA = scrapy.Field()
    total_3P_FGM = scrapy.Field()
    total_3P_FGA = scrapy.Field()
    total_2P_FGM = scrapy.Field()
    total_2P_FGA = scrapy.Field()
    total_FTM = scrapy.Field()
    total_FTA = scrapy.Field()
    total_ORB = scrapy.Field()
    total_DRB = scrapy.Field()
    total_TRB = scrapy.Field()
    total_AST = scrapy.Field()
    total_STL = scrapy.Field()
    total_BLK = scrapy.Field()
    total_TOV = scrapy.Field()
    total_PF = scrapy.Field()
    total_PTS = scrapy.Field()

    per_game_MP = scrapy.Field()
    per_game_FGM = scrapy.Field()
    per_game_FGA = scrapy.Field()
    per_game_3P_FGM = scrapy.Field()
    per_game_3P_FGA = scrapy.Field()
    per_game_2P_FGM = scrapy.Field()
    per_game_2P_FGA = scrapy.Field()
    per_game_FTM = scrapy.Field()
    per_game_FTA = scrapy.Field()
    per_game_ORB = scrapy.Field()
    per_game_DRB = scrapy.Field()
    per_game_TRB = scrapy.Field()
    per_game_AST = scrapy.Field()
    per_game_STL = scrapy.Field()
    per_game_BLK = scrapy.Field()
    per_game_TOV = scrapy.Field()
    per_game_PF = scrapy.Field()
    per_game_PTS = scrapy.Field()
    
    per_36_FGM = scrapy.Field()
    per_36_FGA = scrapy.Field()
    per_36_3P_FGM = scrapy.Field()
    per_36_3P_FGA = scrapy.Field()
    per_36_2P_FGM = scrapy.Field()
    per_36_2P_FGA = scrapy.Field()
    per_36_FTM = scrapy.Field()
    per_36_FTA = scrapy.Field()
    per_36_ORB = scrapy.Field()
    per_36_DRB = scrapy.Field()
    per_36_TRB = scrapy.Field()
    per_36_AST = scrapy.Field()
    per_36_STL = scrapy.Field()
    per_36_BLK = scrapy.Field()
    per_36_TOV = scrapy.Field()
    per_36_PF = scrapy.Field()
    per_36_PTS = scrapy.Field()
    
    per_100_FGM = scrapy.Field()
    per_100_FGA = scrapy.Field()
    per_100_3P_FGM = scrapy.Field()
    per_100_3P_FGA = scrapy.Field()
    per_100_2P_FGM = scrapy.Field()
    per_100_2P_FGA = scrapy.Field()
    per_100_FTM = scrapy.Field()
    per_100_FTA = scrapy.Field()
    per_100_ORB = scrapy.Field()
    per_100_DRB = scrapy.Field()
    per_100_TRB = scrapy.Field()
    per_100_AST = scrapy.Field()
    per_100_STL = scrapy.Field()
    per_100_BLK = scrapy.Field()
    per_100_TOV = scrapy.Field()
    per_100_PF = scrapy.Field()
    per_100_PTS = scrapy.Field()
    per_100_ORTG = scrapy.Field()
    per_100_DRTG = scrapy.Field()

    advanced_PER = scrapy.Field()
    advanced_TS_percent = scrapy.Field()
    advanced_3PAR = scrapy.Field()
    advanced_FTR = scrapy.Field()
    advanced_ORB_percent = scrapy.Field()
    advanced_DRB_percent = scrapy.Field()
    advanced_TRB_percent = scrapy.Field()
    advanced_AST_percent = scrapy.Field()
    advanced_STL_percent = scrapy.Field()
    advanced_BLK_percent = scrapy.Field()
    advanced_TOV_percent = scrapy.Field()
    advanced_USG_percent = scrapy.Field()
    advanced_OWS = scrapy.Field()
    advanced_DWS = scrapy.Field()
    advanced_WS = scrapy.Field()
    advanced_WS48 = scrapy.Field()
    advanced_OBPM = scrapy.Field()
    advanced_DBPM = scrapy.Field()
    advanced_BPM = scrapy.Field()
    advanced_VORP = scrapy.Field()
    
    shooting_dist = scrapy.Field()
    shooting_percent_2P = scrapy.Field()
    shooting_percent_0_3 = scrapy.Field()
    shooting_percent_3_10 = scrapy.Field()
    shooting_percent_10_16 = scrapy.Field()
    # percent of 2P shots that are 16+ feet away
    shooting_percent_16_l3 = scrapy.Field()
    shooting_percent_3P = scrapy.Field()
    shooting_percent_2P = scrapy.Field()
    shooting_FG_percent_0_3 = scrapy.Field()
    shooting_FG_percent_3_10 = scrapy.Field()
    shooting_FG_percent_10_16 = scrapy.Field()
    shooting_FG_percent_16_l3 = scrapy.Field()
    shooting_percent_ast_2P = scrapy.Field()
    # percent FGA that are dunks
    shooting_percent_FG_dunks = scrapy.Field()
    shooting_made_dunks = scrapy.Field()
    shooting_percent_ast_3P = scrapy.Field()
    shooting_percent_3P_corner = scrapy.Field()
    shooting_FG_percent_3P_corner = scrapy.Field()
    
    pbp_PG_percent = scrapy.Field()
    pbp_SG_percent = scrapy.Field()
    pbp_SF_percent = scrapy.Field()
    pbp_PF_percent = scrapy.Field()
    pbp_C_percent = scrapy.Field()
    pbp_plusminus_oncourt = scrapy.Field()
    pbp_plusminus_onoff = scrapy.Field()
    pbp_TOV_badpass = scrapy.Field()
    pbp_TOV_lostball = scrapy.Field()
    pbp_TOV_other = scrapy.Field()
    pbp_shooting_foul_comm = scrapy.Field()
    pbp_blocking_foul_comm = scrapy.Field()
    pbp_offensive_foul_comm = scrapy.Field()
    pbp_take_foul_comm = scrapy.Field()
    pbp_PGA = scrapy.Field()
    pbp_Sfdrawn = scrapy.Field()
    pbp_And1 = scrapy.Field()
    # field goal attempts that are blocked
    pbp_FGA_blocked = scrapy.Field()
    

    playoffs_total_MP = scrapy.Field()
    playoffs_total_FGM = scrapy.Field()
    playoffs_total_FGA = scrapy.Field()
    playoffs_total_FGM = scrapy.Field()
    playoffs_total_FGA = scrapy.Field()
    playoffs_total_FGM = scrapy.Field()
    playoffs_total_FGA = scrapy.Field()
    playoffs_total_FTM = scrapy.Field()
    playoffs_total_FTA = scrapy.Field()
    playoffs_total_ORB = scrapy.Field()
    playoffs_total_DRB = scrapy.Field()
    playoffs_total_TRB = scrapy.Field()
    playoffs_total_AST = scrapy.Field()
    playoffs_total_STL = scrapy.Field()
    playoffs_total_BLK = scrapy.Field()
    playoffs_total_TOV = scrapy.Field()
    playoffs_total_PF = scrapy.Field()
    playoffs_total_PTS = scrapy.Field()
 
    playoffs_per_game_MP = scrapy.Field()
    playoffs_per_game_FGM = scrapy.Field()
    playoffs_per_game_FGA = scrapy.Field()
    playoffs_per_game_FGM = scrapy.Field()
    playoffs_per_game_FGA = scrapy.Field()
    playoffs_per_game_FGM = scrapy.Field()
    playoffs_per_game_FGA = scrapy.Field()
    playoffs_per_game_FTM = scrapy.Field()
    playoffs_per_game_FTA = scrapy.Field()
    playoffs_per_game_ORB = scrapy.Field()
    playoffs_per_game_DRB = scrapy.Field()
    playoffs_per_game_TRB = scrapy.Field()
    playoffs_per_game_AST = scrapy.Field()
    playoffs_per_game_STL = scrapy.Field()
    playoffs_per_game_BLK = scrapy.Field()
    playoffs_per_game_TOV = scrapy.Field()
    playoffs_per_game_PF = scrapy.Field()
    playoffs_per_game_PTS = scrapy.Field()

    playoffs_per_36_MP = scrapy.Field()
    playoffs_per_36_FGM = scrapy.Field()
    playoffs_per_36_FGA = scrapy.Field()
    playoffs_per_36_FGM = scrapy.Field()
    playoffs_per_36_FGA = scrapy.Field()
    playoffs_per_36_FGM = scrapy.Field()
    playoffs_per_36_FGA = scrapy.Field()
    playoffs_per_36_FTM = scrapy.Field()
    playoffs_per_36_FTA = scrapy.Field()
    playoffs_per_36_ORB = scrapy.Field()
    playoffs_per_36_DRB = scrapy.Field()
    playoffs_per_36_TRB = scrapy.Field()
    playoffs_per_36_AST = scrapy.Field()
    playoffs_per_36_STL = scrapy.Field()
    playoffs_per_36_BLK = scrapy.Field()
    playoffs_per_36_TOV = scrapy.Field()
    playoffs_per_36_PF = scrapy.Field()
    playoffs_per_36_PTS = scrapy.Field()
    
    playoffs_per_100_MP = scrapy.Field()
    playoffs_per_100_FGM = scrapy.Field()
    playoffs_per_100_FGA = scrapy.Field()
    playoffs_per_100_3P_FGM = scrapy.Field()
    playoffs_per_100_3P_FGA = scrapy.Field()
    playoffs_per_100_2P_FGM = scrapy.Field()
    playoffs_per_100_2P_FGA = scrapy.Field()
    playoffs_per_100_FTM = scrapy.Field()
    playoffs_per_100_FTA = scrapy.Field()
    playoffs_per_100_ORB = scrapy.Field()
    playoffs_per_100_DRB = scrapy.Field()
    playoffs_per_100_TRB = scrapy.Field()
    playoffs_per_100_AST = scrapy.Field()
    playoffs_per_100_STL = scrapy.Field()
    playoffs_per_100_BLK = scrapy.Field()
    playoffs_per_100_TOV = scrapy.Field()
    playoffs_per_100_PF = scrapy.Field()
    playoffs_per_100_PTS = scrapy.Field()
    playoffs_per_100_ORTG = scrapy.Field()
    playoffs_per_100_DRTG = scrapy.Field()

    playoffs_advanced_PER = scrapy.Field()
    playoffs_advanced_TS_percent = scrapy.Field()
    playoffs_advanced_3PAR = scrapy.Field()
    playoffs_advanced_FTR = scrapy.Field()
    playoffs_advanced_ORB_percent = scrapy.Field()
    playoffs_advanced_DRB_percent = scrapy.Field()
    playoffs_advanced_TRB_percent = scrapy.Field()
    playoffs_advanced_AST_percent = scrapy.Field()
    playoffs_advanced_STL_percent = scrapy.Field()
    playoffs_advanced_BLK_percent = scrapy.Field()
    playoffs_advanced_TOV_percent = scrapy.Field()
    playoffs_advanced_USG_percent = scrapy.Field()
    playoffs_advanced_OWS = scrapy.Field()
    playoffs_advanced_DWS = scrapy.Field()
    playoffs_advanced_WS = scrapy.Field()
    playoffs_advanced_WS48 = scrapy.Field()
    playoffs_advanced_OBPM = scrapy.Field()
    playoffs_advanced_DBPM = scrapy.Field()
    playoffs_advanced_BPM = scrapy.Field()
    playoffs_advanced_VORP = scrapy.Field()

    playoffs_shooting_dist = scrapy.Field()
    playoffs_shooting_percent_2P = scrapy.Field()
    playoffs_shooting_percent_0_3 = scrapy.Field()
    playoffs_shooting_percent_3_10 = scrapy.Field()
    playoffs_shooting_percent_10_16 = scrapy.Field()
    # percent of 2P shots that are 16+ feet away
    playoffs_shooting_percent_16_l3 = scrapy.Field()
    playoffs_shooting_percent_3P = scrapy.Field()
    playoffs_shooting_FG_percent_0_3 = scrapy.Field()
    playoffs_shooting_FG_percent_3_10 = scrapy.Field()
    playoffs_shooting_FG_percent_10_16 = scrapy.Field()
    playoffs_shooting_FG_percent_16_l3 = scrapy.Field()
    playoffs_shooting_percent_ast_2P = scrapy.Field()
    # percent FGA that are dunks
    playoffs_shooting_percent_FG_dunks = scrapy.Field()
    playoffs_shooting_made_dunks = scrapy.Field()
    playoffs_shooting_percent_ast_3P = scrapy.Field()
    playoffs_shooting_percent_3P_corner = scrapy.Field()
    playoffs_shooting_FG_percent_3P_corner = scrapy.Field()
    
    playoffs_pbp_PG_percent = scrapy.Field()
    playoffs_pbp_SG_percent = scrapy.Field()
    playoffs_pbp_SF_percent = scrapy.Field()
    playoffs_pbp_PF_percent = scrapy.Field()
    playoffs_pbp_C_percent = scrapy.Field()
    playoffs_pbp_plusminus_oncourt = scrapy.Field()
    playoffs_pbp_plusminus_onoff = scrapy.Field()
    playoffs_pbp_TOV_badpass = scrapy.Field()
    playoffs_pbp_TOV_lostball = scrapy.Field()
    playoffs_pbp_TOV_other = scrapy.Field()
    playoffs_pbp_PGA = scrapy.Field()
    playoffs_pbp_Sfdrawn = scrapy.Field()
    playoffs_pbp_And1 = scrapy.Field()
    # field goal attempts that are blocked
    playoffs_pbp_FGA_blocked = scrapy.Field()
